apiVersion: v1
metadata:
 name: newcluster
baseDomain: devenv.oci-rhelcert.edge-sro.rhecoeng.com
networking:
 clusterNetwork:
 - cidr: 10.128.0.0/14
   hostPrefix: 23
 networkType: OVNKubernetes
 machineNetwork:
 - cidr: 10.0.0.0/16
 serviceNetwork: 
 - 172.30.0.0/16
compute:
 - architecture: amd64
   hyperthreading: Enabled
   name: worker
   replicas: 0
controlPlane:
 architecture: amd64
 hyperthreading: Enabled
 name: master
 replicas: 3
platform:
 external:
   platformName: oci
   cloudControllerManager: External
sshKey:
pullSecret:
